console.log("external");
alert("External");
let a="str";
let b=23;
let c=345.456;
let d=true;
let e=null;
let f;
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
conkfqsole.log(typeof (a),("\n"),typeof (b));
console.log(typeof b);
console.log(typeof c);
console.log(typeof d);
console.log(typeof e);
console.log(typeof f);
